# coding: utf-8

"""
    YNAB API Endpoints

    Our API uses a REST based design, leverages the JSON data format, and relies upon HTTPS for transport. We respond with meaningful HTTP response codes and if an error occurs, we include error details in the response body.  API Documentation is at https://api.ynab.com

    The version of the OpenAPI document: 1.72.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ynab.api.scheduled_transactions_api import ScheduledTransactionsApi


class TestScheduledTransactionsApi(unittest.TestCase):
    """ScheduledTransactionsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ScheduledTransactionsApi()

    def tearDown(self) -> None:
        pass

    def test_create_scheduled_transaction(self) -> None:
        """Test case for create_scheduled_transaction

        Create a single scheduled transaction
        """
        pass

    def test_get_scheduled_transaction_by_id(self) -> None:
        """Test case for get_scheduled_transaction_by_id

        Single scheduled transaction
        """
        pass

    def test_get_scheduled_transactions(self) -> None:
        """Test case for get_scheduled_transactions

        List scheduled transactions
        """
        pass


if __name__ == '__main__':
    unittest.main()
