# coding: utf-8

"""
    YNAB API Endpoints

    Our API uses a REST based design, leverages the JSON data format, and relies upon HTTPS for transport. We respond with meaningful HTTP response codes and if an error occurs, we include error details in the response body.  API Documentation is at https://api.ynab.com

    The version of the OpenAPI document: 1.72.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ynab.models.account_type import AccountType

class TestAccountType(unittest.TestCase):
    """AccountType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAccountType(self):
        """Test AccountType"""
        # inst = AccountType()

if __name__ == '__main__':
    unittest.main()
