# coding: utf-8

"""
    YNAB API Endpoints

    Our API uses a REST based design, leverages the JSON data format, and relies upon HTTPS for transport. We respond with meaningful HTTP response codes and if an error occurs, we include error details in the response body.  API Documentation is at https://api.ynab.com

    The version of the OpenAPI document: 1.81.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ynab.models.save_category_group_response import SaveCategoryGroupResponse

class TestSaveCategoryGroupResponse(unittest.TestCase):
    """SaveCategoryGroupResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SaveCategoryGroupResponse:
        """Test SaveCategoryGroupResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SaveCategoryGroupResponse`
        """
        model = SaveCategoryGroupResponse()
        if include_optional:
            return SaveCategoryGroupResponse(
                data = ynab.models.save_category_group_response_data.SaveCategoryGroupResponse_data(
                    category_group = ynab.models.category_group.CategoryGroup(
                        id = '', 
                        name = '', 
                        hidden = True, 
                        deleted = True, ), 
                    server_knowledge = 56, )
            )
        else:
            return SaveCategoryGroupResponse(
                data = ynab.models.save_category_group_response_data.SaveCategoryGroupResponse_data(
                    category_group = ynab.models.category_group.CategoryGroup(
                        id = '', 
                        name = '', 
                        hidden = True, 
                        deleted = True, ), 
                    server_knowledge = 56, ),
        )
        """

    def testSaveCategoryGroupResponse(self):
        """Test SaveCategoryGroupResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
