# coding: utf-8

"""
    YNAB API Endpoints

    Our API uses a REST based design, leverages the JSON data format, and relies upon HTTPS for transport. We respond with meaningful HTTP response codes and if an error occurs, we include error details in the response body.  API Documentation is at https://api.ynab.com

    The version of the OpenAPI document: 1.72.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ynab.api.payees_api import PayeesApi


class TestPayeesApi(unittest.TestCase):
    """PayeesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = PayeesApi()

    def tearDown(self) -> None:
        pass

    def test_get_payee_by_id(self) -> None:
        """Test case for get_payee_by_id

        Single payee
        """
        pass

    def test_get_payees(self) -> None:
        """Test case for get_payees

        List payees
        """
        pass

    def test_update_payee(self) -> None:
        """Test case for update_payee

        Update a payee
        """
        pass


if __name__ == '__main__':
    unittest.main()
