# coding: utf-8

"""
    YNAB API Endpoints

    Our API uses a REST based design, leverages the JSON data format, and relies upon HTTPS for transport. We respond with meaningful HTTP response codes and if an error occurs, we include error details in the response body.  API Documentation is at https://api.ynab.com

    The version of the OpenAPI document: 1.81.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ynab.api.plans_api import PlansApi


class TestPlansApi(unittest.TestCase):
    """PlansApi unit test stubs"""

    def setUp(self) -> None:
        self.api = PlansApi()

    def tearDown(self) -> None:
        pass

    def test_get_plan_by_id(self) -> None:
        """Test case for get_plan_by_id

        Get a plan
        """
        pass

    def test_get_plan_settings_by_id(self) -> None:
        """Test case for get_plan_settings_by_id

        Get plan settings
        """
        pass

    def test_get_plans(self) -> None:
        """Test case for get_plans

        Get all plans
        """
        pass


if __name__ == '__main__':
    unittest.main()
