# coding: utf-8

"""
    YNAB API Endpoints

    Our API uses a REST based design, leverages the JSON data format, and relies upon HTTPS for transport. We respond with meaningful HTTP response codes and if an error occurs, we include error details in the response body.  API Documentation is at https://api.ynab.com

    The version of the OpenAPI document: 1.72.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ynab.api.categories_api import CategoriesApi


class TestCategoriesApi(unittest.TestCase):
    """CategoriesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = CategoriesApi()

    def tearDown(self) -> None:
        pass

    def test_get_categories(self) -> None:
        """Test case for get_categories

        List categories
        """
        pass

    def test_get_category_by_id(self) -> None:
        """Test case for get_category_by_id

        Single category
        """
        pass

    def test_get_month_category_by_id(self) -> None:
        """Test case for get_month_category_by_id

        Single category for a specific budget month
        """
        pass

    def test_update_category(self) -> None:
        """Test case for update_category

        Update a category
        """
        pass

    def test_update_month_category(self) -> None:
        """Test case for update_month_category

        Update a category for a specific month
        """
        pass


if __name__ == '__main__':
    unittest.main()
