# coding: utf-8

"""
    YNAB API Endpoints

    Our API uses a REST based design, leverages the JSON data format, and relies upon HTTPS for transport. We respond with meaningful HTTP response codes and if an error occurs, we include error details in the response body.  API Documentation is at https://api.ynab.com

    The version of the OpenAPI document: 1.81.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ynab.models.money_movement_group import MoneyMovementGroup

class TestMoneyMovementGroup(unittest.TestCase):
    """MoneyMovementGroup unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MoneyMovementGroup:
        """Test MoneyMovementGroup
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MoneyMovementGroup`
        """
        model = MoneyMovementGroup()
        if include_optional:
            return MoneyMovementGroup(
                id = '',
                group_created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                month = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                note = '',
                performed_by_user_id = ''
            )
        else:
            return MoneyMovementGroup(
                id = '',
                group_created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                month = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
        )
        """

    def testMoneyMovementGroup(self):
        """Test MoneyMovementGroup"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
