# coding: utf-8

"""
    YNAB API Endpoints

    Our API uses a REST based design, leverages the JSON data format, and relies upon HTTPS for transport. We respond with meaningful HTTP response codes and if an error occurs, we include error details in the response body.  API Documentation is at https://api.ynab.com

    The version of the OpenAPI document: 1.72.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ynab.api.budgets_api import BudgetsApi


class TestBudgetsApi(unittest.TestCase):
    """BudgetsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = BudgetsApi()

    def tearDown(self) -> None:
        pass

    def test_get_budget_by_id(self) -> None:
        """Test case for get_budget_by_id

        Single budget
        """
        pass

    def test_get_budget_settings_by_id(self) -> None:
        """Test case for get_budget_settings_by_id

        Budget Settings
        """
        pass

    def test_get_budgets(self) -> None:
        """Test case for get_budgets

        List budgets
        """
        pass


if __name__ == '__main__':
    unittest.main()
