# coding: utf-8

"""
    YNAB API Endpoints

    Our API uses a REST based design, leverages the JSON data format, and relies upon HTTPS for transport. We respond with meaningful HTTP response codes and if an error occurs, we include error details in the response body.  API Documentation is at https://api.ynab.com

    The version of the OpenAPI document: 1.81.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ynab.api.money_movements_api import MoneyMovementsApi


class TestMoneyMovementsApi(unittest.TestCase):
    """MoneyMovementsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = MoneyMovementsApi()

    def tearDown(self) -> None:
        pass

    def test_get_money_movement_groups(self) -> None:
        """Test case for get_money_movement_groups

        Get all money movement groups
        """
        pass

    def test_get_money_movement_groups_by_month(self) -> None:
        """Test case for get_money_movement_groups_by_month

        Get money movement groups for a plan month
        """
        pass

    def test_get_money_movements(self) -> None:
        """Test case for get_money_movements

        Get all money movements
        """
        pass

    def test_get_money_movements_by_month(self) -> None:
        """Test case for get_money_movements_by_month

        Get money movements for a plan month
        """
        pass


if __name__ == '__main__':
    unittest.main()
