# coding: utf-8

"""
    YNAB API Endpoints

    Our API uses a REST based design, leverages the JSON data format, and relies upon HTTPS for transport. We respond with meaningful HTTP response codes and if an error occurs, we include error details in the response body.  API Documentation is at https://api.ynab.com

    The version of the OpenAPI document: 1.72.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ynab.models.budget_summary_response_data import BudgetSummaryResponseData

class TestBudgetSummaryResponseData(unittest.TestCase):
    """BudgetSummaryResponseData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BudgetSummaryResponseData:
        """Test BudgetSummaryResponseData
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BudgetSummaryResponseData`
        """
        model = BudgetSummaryResponseData()
        if include_optional:
            return BudgetSummaryResponseData(
                budgets = [
                    ynab.models.budget_summary.BudgetSummary(
                        id = '', 
                        name = '', 
                        last_modified_on = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        first_month = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                        last_month = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                        date_format = ynab.models.date_format.DateFormat(
                            format = '', ), 
                        currency_format = ynab.models.currency_format.CurrencyFormat(
                            iso_code = '', 
                            example_format = '', 
                            decimal_digits = 56, 
                            decimal_separator = '', 
                            symbol_first = True, 
                            group_separator = '', 
                            currency_symbol = '', 
                            display_symbol = True, ), 
                        accounts = [
                            ynab.models.account.Account(
                                id = '', 
                                name = '', 
                                type = 'checking', 
                                on_budget = True, 
                                closed = True, 
                                note = '', 
                                balance = 56, 
                                cleared_balance = 56, 
                                uncleared_balance = 56, 
                                transfer_payee_id = '', 
                                direct_import_linked = True, 
                                direct_import_in_error = True, 
                                last_reconciled_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                debt_original_balance = 56, 
                                debt_interest_rates = {
                                    'key' : 56
                                    }, 
                                debt_minimum_payments = {
                                    'key' : 56
                                    }, 
                                debt_escrow_amounts = , 
                                deleted = True, )
                            ], )
                    ],
                default_budget = ynab.models.budget_summary.BudgetSummary(
                    id = '', 
                    name = '', 
                    last_modified_on = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    first_month = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                    last_month = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                    date_format = ynab.models.date_format.DateFormat(
                        format = '', ), 
                    currency_format = ynab.models.currency_format.CurrencyFormat(
                        iso_code = '', 
                        example_format = '', 
                        decimal_digits = 56, 
                        decimal_separator = '', 
                        symbol_first = True, 
                        group_separator = '', 
                        currency_symbol = '', 
                        display_symbol = True, ), 
                    accounts = [
                        ynab.models.account.Account(
                            id = '', 
                            name = '', 
                            type = 'checking', 
                            on_budget = True, 
                            closed = True, 
                            note = '', 
                            balance = 56, 
                            cleared_balance = 56, 
                            uncleared_balance = 56, 
                            transfer_payee_id = '', 
                            direct_import_linked = True, 
                            direct_import_in_error = True, 
                            last_reconciled_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            debt_original_balance = 56, 
                            debt_interest_rates = {
                                'key' : 56
                                }, 
                            debt_minimum_payments = {
                                'key' : 56
                                }, 
                            debt_escrow_amounts = , 
                            deleted = True, )
                        ], )
            )
        else:
            return BudgetSummaryResponseData(
                budgets = [
                    ynab.models.budget_summary.BudgetSummary(
                        id = '', 
                        name = '', 
                        last_modified_on = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        first_month = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                        last_month = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                        date_format = ynab.models.date_format.DateFormat(
                            format = '', ), 
                        currency_format = ynab.models.currency_format.CurrencyFormat(
                            iso_code = '', 
                            example_format = '', 
                            decimal_digits = 56, 
                            decimal_separator = '', 
                            symbol_first = True, 
                            group_separator = '', 
                            currency_symbol = '', 
                            display_symbol = True, ), 
                        accounts = [
                            ynab.models.account.Account(
                                id = '', 
                                name = '', 
                                type = 'checking', 
                                on_budget = True, 
                                closed = True, 
                                note = '', 
                                balance = 56, 
                                cleared_balance = 56, 
                                uncleared_balance = 56, 
                                transfer_payee_id = '', 
                                direct_import_linked = True, 
                                direct_import_in_error = True, 
                                last_reconciled_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                debt_original_balance = 56, 
                                debt_interest_rates = {
                                    'key' : 56
                                    }, 
                                debt_minimum_payments = {
                                    'key' : 56
                                    }, 
                                debt_escrow_amounts = , 
                                deleted = True, )
                            ], )
                    ],
        )
        """

    def testBudgetSummaryResponseData(self):
        """Test BudgetSummaryResponseData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
