packageName: ynab
packageVersion: 1.0.0
packageDescription: Official Python client for the YNAB API. API documentation available at https://api.ynab.com.
licenseInfo:
  name: Apache-2.0
  url: https://www.apache.org/licenses/LICENSE-2.0.html