# coding: utf-8

"""
    YNAB API Endpoints

    Our API uses a REST based design, leverages the JSON data format, and relies upon HTTPS for transport. We respond with meaningful HTTP response codes and if an error occurs, we include error details in the response body.  API Documentation is at https://api.ynab.com

    The version of the OpenAPI document: 1.78.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import date, datetime
from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from uuid import UUID
from typing import Optional, Set
from typing_extensions import Self

class MoneyMovement(BaseModel):
    """
    MoneyMovement
    """ # noqa: E501
    id: UUID
    month: Optional[date] = Field(default=None, description="The month of the money movement in ISO format (e.g. 2024-01-01)")
    moved_at: Optional[datetime] = Field(default=None, description="The date/time the money movement was processed on the server in ISO format (e.g. 2024-01-01T12:00:00Z)")
    note: Optional[StrictStr] = None
    money_movement_group_id: Optional[UUID] = Field(default=None, description="The id of the money movement group this movement belongs to")
    performed_by_user_id: Optional[UUID] = Field(default=None, description="The id of the user who performed the money movement")
    from_category_id: Optional[UUID] = Field(default=None, description="The id of the category the money was moved from")
    to_category_id: Optional[UUID] = Field(default=None, description="The id of the category the money was moved to")
    amount: StrictInt = Field(description="The amount of the money movement in milliunits format")
    __properties: ClassVar[List[str]] = ["id", "month", "moved_at", "note", "money_movement_group_id", "performed_by_user_id", "from_category_id", "to_category_id", "amount"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of MoneyMovement from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if month (nullable) is None
        # and model_fields_set contains the field
        if self.month is None and "month" in self.model_fields_set:
            _dict['month'] = None

        # set to None if moved_at (nullable) is None
        # and model_fields_set contains the field
        if self.moved_at is None and "moved_at" in self.model_fields_set:
            _dict['moved_at'] = None

        # set to None if note (nullable) is None
        # and model_fields_set contains the field
        if self.note is None and "note" in self.model_fields_set:
            _dict['note'] = None

        # set to None if money_movement_group_id (nullable) is None
        # and model_fields_set contains the field
        if self.money_movement_group_id is None and "money_movement_group_id" in self.model_fields_set:
            _dict['money_movement_group_id'] = None

        # set to None if performed_by_user_id (nullable) is None
        # and model_fields_set contains the field
        if self.performed_by_user_id is None and "performed_by_user_id" in self.model_fields_set:
            _dict['performed_by_user_id'] = None

        # set to None if from_category_id (nullable) is None
        # and model_fields_set contains the field
        if self.from_category_id is None and "from_category_id" in self.model_fields_set:
            _dict['from_category_id'] = None

        # set to None if to_category_id (nullable) is None
        # and model_fields_set contains the field
        if self.to_category_id is None and "to_category_id" in self.model_fields_set:
            _dict['to_category_id'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of MoneyMovement from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "month": obj.get("month"),
            "moved_at": obj.get("moved_at"),
            "note": obj.get("note"),
            "money_movement_group_id": obj.get("money_movement_group_id"),
            "performed_by_user_id": obj.get("performed_by_user_id"),
            "from_category_id": obj.get("from_category_id"),
            "to_category_id": obj.get("to_category_id"),
            "amount": obj.get("amount")
        })
        return _obj


