# coding: utf-8

"""
    YNAB API Endpoints

    Our API uses a REST based design, leverages the JSON data format, and relies upon HTTPS for transport. We respond with meaningful HTTP response codes and if an error occurs, we include error details in the response body.  API Documentation is at https://api.ynab.com

    The version of the OpenAPI document: 1.83.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from uuid import UUID
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class ScheduledSubTransaction(BaseModel):
    """
    ScheduledSubTransaction
    """ # noqa: E501
    id: UUID
    scheduled_transaction_id: UUID
    amount: StrictInt = Field(description="The scheduled subtransaction amount in milliunits format")
    memo: Optional[StrictStr] = None
    payee_id: Optional[UUID] = None
    payee_name: Optional[StrictStr] = None
    category_id: Optional[UUID] = None
    category_name: Optional[StrictStr] = None
    transfer_account_id: Optional[UUID] = Field(default=None, description="If a transfer, the account_id which the scheduled subtransaction transfers to")
    deleted: StrictBool = Field(description="Whether or not the scheduled subtransaction has been deleted. Deleted scheduled subtransactions will only be included in delta requests.")
    amount_formatted: Optional[StrictStr] = Field(default=None, description="The scheduled subtransaction amount formatted in the plan's currency format")
    amount_currency: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="The scheduled subtransaction amount as a decimal currency amount")
    __properties: ClassVar[List[str]] = ["id", "scheduled_transaction_id", "amount", "memo", "payee_id", "payee_name", "category_id", "category_name", "transfer_account_id", "deleted", "amount_formatted", "amount_currency"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ScheduledSubTransaction from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ScheduledSubTransaction from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "scheduled_transaction_id": obj.get("scheduled_transaction_id"),
            "amount": obj.get("amount"),
            "memo": obj.get("memo"),
            "payee_id": obj.get("payee_id"),
            "payee_name": obj.get("payee_name"),
            "category_id": obj.get("category_id"),
            "category_name": obj.get("category_name"),
            "transfer_account_id": obj.get("transfer_account_id"),
            "deleted": obj.get("deleted"),
            "amount_formatted": obj.get("amount_formatted"),
            "amount_currency": obj.get("amount_currency")
        })
        return _obj


