name: Publish
on:
  workflow_dispatch:
    inputs:
      version_type:
        type: choice
        description: Version type
        default: minor
        options:
        - major
        - minor
        - patch
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup git repo
        run: |
          git config user.name $GITHUB_ACTOR
          git config user.email gh-actions-${GITHUB_ACTOR}@github.com
          git remote add gh-origin https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12
      - name: Install dependencies
        run: |
          pip install poetry
          poetry install
      - name: Bump Version
        id: bump_version 
        run: |
          NEW_VERSION=$(python scripts/update_version.py ${{ github.event.inputs.version_type }})
          echo "NEW_VERSION=$NEW_VERSION"
          echo "new_version=$(echo $NEW_VERSION)" >> $GITHUB_OUTPUT                   
      - name: Generate with new version
        run: ./scripts/generate.sh
      - name: Build
        run: poetry build
      - name: Commit and push changes
        run: |
          git add ynab/configuration.py ynab/api_client.py ynab/__init__.py pyproject.toml openapi-generator-config.yaml
          git commit -m 'Bumping version for ${{ steps.bump_version.outputs.new_version }}'
          git push gh-origin HEAD:main
      - name: Publish to PyPI
        env:
          POETRY_PYPI_TOKEN_PYPI: ${{ secrets.POETRY_PYPI_TOKEN_PYPI }}
        run: poetry publish      
      - name: Create a Release
        id: create-release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.bump_version.outputs.new_version }}
          generate_release_notes: true
      - name: Comment on PRs with link to release they are included in
        uses: actions/github-script@v6
        env:
          RELEASE_ID: ${{ steps.create-release.outputs.id }}
        with:
          script: |
            const releaseId = process.env.RELEASE_ID;
            console.log(`Fetching release_id: ${releaseId} ...`);
            const getReleaseResponse = await github.rest.repos.getRelease({
              release_id: process.env.RELEASE_ID,
              owner: context.repo.owner,
              repo: context.repo.repo
            });
            const release = getReleaseResponse.data;

            const prNumbersInRelease = new Set(Array.from(release.body.matchAll(/\/pull\/(\d+)/g)).map(p=>p[1]));

            for(let prNumber of prNumbersInRelease) {
              console.log(`Adding comment on PR #${prNumber} ...`);
              await github.rest.issues.createComment({
                issue_number: prNumber,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: `The changes in this PR were just released in [${release.name}](https://github.com/${context.repo.owner}/${context.repo.repo}/releases/tag/${release.tag_name}) 🎉.`
              })
            }
